alias please='sudo'
alias ls='ls -FlaGh'
alias mkdir='mkdir -p'
alias resource='source ~/.zshrc'
alias m='mvim'
alias s='subl3'
alias s3='subl3'
alias gs='gst'
alias gerp='grep'

# alias uu='cd ~/Code/universal-uclick'
# alias kreeger='cd ~/Code/kreeger'
alias ftw='cd ~/Code/ftw'
alias fs='foreman start'

alias bz2='tar --exclude ".git/" -cvjf'
